# Generated by Django 3.0.3 on 2020-03-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='session',
            field=models.CharField(default='pre-sessions', max_length=36),
            preserve_default=False,
        ),
    ]
