version: '3'
services:
  web:
    build:
      context: .
      dockerfile:  ./docker/django_server/Dockerfile
    command: bash -c "python manage.py migrate && python manage.py collectstatic --noinput && uwsgi --socket 0.0.0.0:8001 --enable-threads --module backend.wsgi"
    ports:
     - "8001:8001"
    volumes:
      - ./static_vol:/srv/back/static
    restart: always
  nginx:
    build:
      context: .
      dockerfile:  ./docker/nginx/Dockerfile
    ports:
     - "8085:80"
    restart: always
    volumes:
        - ./static_vol:/srv/back/static